# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#           docker compose down
#
#           http://localhost:8080
#
# evtl.:    docker compose exec keycloak bash

---
# https://docs.docker.com/compose/compose-file
# https://docs.docker.com/compose/compose-file/compose-file-v3
services:
  keycloak:
    image: jboss/keycloak:15.1.0
    ports:
      - published: 8080
        target: 8080
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/keycloak
        target: /opt/jboss/keycloak/standalone/data
    environment:
      TZ: Europe/Berlin
    container_name: keycloak
    hostname: keycloak
    user: jboss
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
